package main

import (
	"fmt"
	"time"
)

func testList() {
	testList := NewList()
	start := time.Now()
	testList.AddItem(3, 100)
	end := time.Now()
	str := testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 200)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 250)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5, 200)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5, 300)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5, 50)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 40)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 400)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3, 300)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3, 600)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3, 300)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(1, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(6, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(7, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(6, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 300)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4, 100)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
}
