package main

import (
	"fmt"
	"time"
)

func testList() {
	testList := NewList()
	start := time.Now()
	testList.AddItem(3)
	end := time.Now()
	str := testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(3)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(1)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(6)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(7)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(6)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(5)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
	start = time.Now()
	testList.AddItem(4)
	end = time.Now()
	str = testList.ToString()
	fmt.Println(str, "in", end.Sub(start))
}
