package main

import (
	"fmt"
)

func testList() {
	testList := NewList()
	testList.AddItem(3)
	str := testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(5)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(5)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(5)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(3)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(3)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(3)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(3)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(1)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(6)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(7)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(6)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(5)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
	testList.AddItem(4)
	str = testList.ToString()
	fmt.Println(str)
}
