name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install
      run: make install

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Archive documents
      uses: actions/upload-artifact@v2
      with:
        name: documents
        path: documents
